### ISSUE TITLE
تغییر دامنه ها و اضافه کردن دامنه‌های جدید

### ISSUE THREAD

**Issue by RaminNietzsche** [arvancloud/arvans3#9]
با توجه به تغییر دامنه‌ها و اضافه شدن دامنه‌ی جدید نیاز هست تا این بخش به‌روزرسانی بشه 

https://github.com/arvancloud/arvans3/blob/8214aa139928a84b4e97b37e0e62c7f4773411a2/src/dialogs/ProfileDialog/ProfileDialog.js#L127

**Comment by ehsantdy** [comment]
@nosaraei
